import './globals.scss';
import localFont from 'next/font/local';
import { cookies } from 'next/headers';
import Link from 'next/link';
import type { ReactNode } from 'react';
import { getUser } from '../database/users';
import LogoutButton from './(auth)/logout/LogoutButton';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const dynamic = 'force-dynamic';

export const metadata = {
  title: {
    default: 'Home | UpLeveled',
    template: '%s | UpLeveled',
  },

  description: 'Generated by create next app',
};

type Props = {
  children: ReactNode;
};

export default async function RootLayout({ children }: Props) {
  // Task: Display the logged in user's username in the navigation bar and hide the login and register links depending on whether the user is logged in or not
  // 1. Checking if the sessionToken cookie exists
  const sessionTokenCookie = (await cookies()).get('sessionToken');

  // 2. Get the current logged in user from the database using the sessionToken value
  const user = sessionTokenCookie && (await getUser(sessionTokenCookie.value));

  console.log('User: ', user);

  // 3. Make decision whether to show the login and register links or not

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>
          <div>
            <nav>
              {/* This is not optimized */}
              {/* <a href="/about">About</a> */}

              {/* This is optimized */}
              <Link href="/">Home</Link>
              <Link href="/animals">Animals</Link>
              <Link href="/animals/dashboard">Dashboard</Link>
              <Link href="/fruits">Fruits</Link>
              <Link href="/about">About</Link>

              <div>
                {user ? (
                  <>
                    <Link href={`/profile/${user.username}`}>
                      {user.username}
                    </Link>
                    <Link href="/notes">View Notes</Link>
                    <LogoutButton />
                  </>
                ) : (
                  <>
                    <Link href="/register">Register</Link>
                    <Link href="/login">Login</Link>
                  </>
                )}
              </div>
            </nav>
            {Math.floor(Math.random() * 10)}
          </div>
        </header>
        <main>{children}</main>
        <footer>Footer</footer>
      </body>
    </html>
  );
}
